using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NextTurn.Domain.Queue.Entities;
using NextTurn.Domain.Queue.Enums;
using QueueEntity = NextTurn.Domain.Queue.Entities.Queue;

namespace NextTurn.Infrastructure.Persistence.Configurations.Queue;

/// <summary>
/// EF Core Fluent API configuration for the QueueEntry child entity.
/// Maps domain properties to the QueueEntries table.
///
/// Tenant isolation:
///   QueueEntry has no TenantId column of its own. Isolation is enforced via a
///   global query filter that correlated-subqueries through Queue.OrganisationId,
///   configured in ApplicationDbContext.OnModelCreating.
///   All repository queries also explicitly filter by QueueId, which is resolved
///   from a tenant-filtered Queue lookup — defence in depth.
/// </summary>
public class QueueEntryConfiguration : IEntityTypeConfiguration<QueueEntry>
{
    public void Configure(EntityTypeBuilder<QueueEntry> builder)
    {
        builder.ToTable("QueueEntries");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Id)
            .ValueGeneratedNever(); // GUID generated by QueueEntry.Create(), not the DB

        builder.Property(e => e.QueueId)
            .IsRequired();

        builder.Property(e => e.UserId)
            .IsRequired();

        builder.Property(e => e.TicketNumber)
            .IsRequired();

        // Store Status as a string (e.g. "Waiting") — consistent with other enum columns.
        builder.Property(e => e.Status)
            .IsRequired()
            .HasMaxLength(20)
            .HasConversion<string>()
            .HasDefaultValue(QueueEntryStatus.Waiting);

        builder.Property(e => e.JoinedAt)
            .IsRequired();

        // Relationship: QueueEntry → Queue (many-to-one).
        // No navigation property on QueueEntry — we reference QueueEntity by type only.
        // This is an EF Core feature: relationships can be configured without nav properties
        // on one or both sides (useful when keeping domain entities free of EF concerns).
        builder.HasOne<QueueEntity>()
            .WithMany()
            .HasForeignKey(e => e.QueueId)
            .OnDelete(DeleteBehavior.Cascade); // deleting a queue removes all its entries

        // Composite index covering the two most common query predicates:
        // - GetActiveEntryCountAsync: WHERE QueueId = ? AND Status IN (Waiting, Serving)
        // - HasActiveEntryAsync:      WHERE QueueId = ? AND UserId = ? AND Status IN (...)
        builder.HasIndex(e => new { e.QueueId, e.Status })
            .HasDatabaseName("IX_QueueEntries_QueueId_Status");

        // Separate index for the HasActiveEntryAsync duplicate-join check.
        builder.HasIndex(e => new { e.QueueId, e.UserId })
            .HasDatabaseName("IX_QueueEntries_QueueId_UserId");

        // Enforce "at most one Serving entry per queue" at the DB layer.
        // The filtered unique index is a concurrency safety net for parallel staff actions.
        builder.HasIndex(e => e.QueueId)
            .HasDatabaseName("UX_QueueEntries_QueueId_OneServing")
            .IsUnique()
            .HasFilter("[Status] = 'Serving'");
    }
}
