using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NextTurn.Domain.Queue.Enums;
using QueueEntity = NextTurn.Domain.Queue.Entities.Queue;

namespace NextTurn.Infrastructure.Persistence.Configurations.Queue;

/// <summary>
/// EF Core Fluent API configuration for the Queue aggregate root.
/// Maps domain properties to the Queues table.
/// </summary>
public class QueueConfiguration : IEntityTypeConfiguration<QueueEntity>
{
    public void Configure(EntityTypeBuilder<QueueEntity> builder)
    {
        builder.ToTable("Queues");

        builder.HasKey(q => q.Id);

        builder.Property(q => q.Id)
            .ValueGeneratedNever(); // GUID generated by Queue.Create(), not the DB

        builder.Property(q => q.OrganisationId)
            .IsRequired();

        // Index used by the tenant global query filter — nearly every queue query
        // filters on OrganisationId, so this index pays for itself immediately.
        builder.HasIndex(q => q.OrganisationId)
            .HasDatabaseName("IX_Queues_OrganisationId");

        builder.Property(q => q.Name)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(q => q.MaxCapacity)
            .IsRequired();

        builder.Property(q => q.AverageServiceTimeSeconds)
            .IsRequired();

        // Store Status as a string (e.g. "Active") — self-documenting in the DB,
        // safe against enum value reordering. Consistent with User.Role and Organisation.Status.
        builder.Property(q => q.Status)
            .IsRequired()
            .HasMaxLength(20)
            .HasConversion<string>()
            .HasDefaultValue(QueueStatus.Active);

        builder.Property(q => q.CreatedAt)
            .IsRequired();
    }
}
