using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NextTurn.API.Models.Organisations;
using NextTurn.Application.Organisation.Commands.RegisterOrganisation;
using NextTurn.Application.Organisation.Queries.ResolveOrganisationLogin;
using NextTurn.Application.Organisation.Queries.ResolveOrganisationTenant;

namespace NextTurn.API.Controllers;

/// <summary>
/// Handles organisation resource endpoints.
///
/// The controller is intentionally thin — it:
///   1. Accepts the HTTP request and maps it to a command
///   2. Sends through MediatR
///   3. Maps the result to an HTTP response
///
/// All business logic lives in the Application layer handlers.
/// </summary>
[ApiController]
[Route("api/organisations")]
public sealed class OrganisationsController : ControllerBase
{
    private readonly ISender _sender;

    public OrganisationsController(ISender sender)
    {
        _sender = sender;
    }

    /// <summary>
    /// Register a new organisation and create its initial OrgAdmin account.
    /// </summary>
    /// <remarks>
    /// This is a public, unauthenticated endpoint — the organisation does not yet
    /// exist in the system, so there is no tenant context to authenticate against.
    ///
    /// On success, returns 201 Created with the IDs of the newly-created organisation
    /// and admin user, plus a Location header pointing to the organisation resource.
    ///
    /// A temporary password is generated by the handler and sent to the admin email
    /// address via IEmailService (stub in Sprint 1 — logs only).
    ///
    /// Error responses:
    ///   409 — organisation name already registered (ConflictDomainException)
    ///   400 — other domain rule violated (DomainException)
    ///   422 — input validation failed (FluentValidation)
    /// </remarks>
    [HttpPost]
    [AllowAnonymous]
    [ProducesResponseType(StatusCodes.Status201Created)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status409Conflict)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status422UnprocessableEntity)]
    public async Task<IActionResult> RegisterOrganisation(
        [FromBody] RegisterOrganisationRequest request,
        CancellationToken cancellationToken)
    {
        var command = new RegisterOrganisationCommand(
            request.OrgName,
            request.AddressLine1,
            request.City,
            request.PostalCode,
            request.Country,
            request.OrgType,
            request.AdminName,
            request.AdminEmail);

        var result = await _sender.Send(command, cancellationToken);

        return Created(
            $"/api/organisations/{result.OrganisationId}",
            new { result.OrganisationId, result.AdminUserId, result.LoginPath });
    }

    /// <summary>
    /// Resolve an organisation admin login path from an admin email address.
    /// </summary>
    [HttpPost("resolve-login")]
    [AllowAnonymous]
    [ProducesResponseType(typeof(ResolveOrganisationLoginResult), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status422UnprocessableEntity)]
    public async Task<IActionResult> ResolveLogin(
        [FromBody] ResolveOrganisationLoginRequest request,
        CancellationToken cancellationToken)
    {
        var query = new ResolveOrganisationLoginQuery(request.AdminEmail);
        var result = await _sender.Send(query, cancellationToken);

        return Ok(result);
    }

    /// <summary>
    /// Resolve organisation tenant details from a public organisation login slug.
    /// </summary>
    [HttpGet("resolve-tenant")]
    [AllowAnonymous]
    [ProducesResponseType(typeof(ResolveOrganisationTenantResult), StatusCodes.Status200OK)]
    [ProducesResponseType(typeof(ProblemDetails), StatusCodes.Status400BadRequest)]
    [ProducesResponseType(typeof(ValidationProblemDetails), StatusCodes.Status422UnprocessableEntity)]
    public async Task<IActionResult> ResolveTenant(
        [FromQuery] string slug,
        CancellationToken cancellationToken)
    {
        var query = new ResolveOrganisationTenantQuery(slug);
        var result = await _sender.Send(query, cancellationToken);
        return Ok(result);
    }
}
