using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NextTurn.Domain.Organisation.Enums;
using OrganisationEntity = NextTurn.Domain.Organisation.Entities.Organisation;

namespace NextTurn.Infrastructure.Persistence.Configurations.Organisation;

/// <summary>
/// EF Core Fluent API configuration for the Organisation aggregate root.
/// Maps domain properties to the Organisations table.
/// The Address value object is stored as owned-type columns (no separate table).
/// </summary>
public class OrganisationConfiguration : IEntityTypeConfiguration<OrganisationEntity>
{
    public void Configure(EntityTypeBuilder<OrganisationEntity> builder)
    {
        builder.ToTable("Organisations");

        builder.HasKey(o => o.Id);

        builder.Property(o => o.Id)
            .ValueGeneratedNever(); // GUID generated by Organisation.Create(), not the DB

        builder.Property(o => o.Name)
            .IsRequired()
            .HasMaxLength(200);

        builder.Property(o => o.Slug)
            .IsRequired()
            .HasMaxLength(64);

        // Unique index on Name — enforced at the DB level as a safety net.
        // The duplicate-name check in the command handler fires first (domain boundary).
        builder.HasIndex(o => o.Name)
            .IsUnique()
            .HasDatabaseName("IX_Organisations_Name");

        builder.HasIndex(o => o.Slug)
            .IsUnique()
            .HasDatabaseName("IX_Organisations_Slug");

        // Store Status as a string (e.g. "PendingApproval") — self-documenting in the DB.
        builder.Property(o => o.Status)
            .IsRequired()
            .HasMaxLength(30)
            .HasConversion<string>()
            .HasDefaultValue(OrganisationStatus.PendingApproval);

        // Store Type as a string (e.g. "Healthcare") — survives enum value reordering.
        builder.Property(o => o.Type)
            .IsRequired()
            .HasMaxLength(30)
            .HasConversion<string>();

        // AdminEmail is an EmailAddress value object — owned type, column in the same table.
        builder.OwnsOne(o => o.AdminEmail, emailBuilder =>
        {
            emailBuilder.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(254)
                .HasColumnName("AdminEmail");
        });

        // Address is a value object — four columns stored inline on Organisations.
        builder.OwnsOne(o => o.Address, addressBuilder =>
        {
            addressBuilder.Property(a => a.Line1)
                .IsRequired()
                .HasMaxLength(300)
                .HasColumnName("AddressLine1");

            addressBuilder.Property(a => a.City)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("AddressCity");

            addressBuilder.Property(a => a.PostalCode)
                .IsRequired()
                .HasMaxLength(20)
                .HasColumnName("AddressPostalCode");

            addressBuilder.Property(a => a.Country)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("AddressCountry");
        });

        builder.Property(o => o.CreatedAt)
            .IsRequired();
    }
}
