using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NextTurn.Domain.Auth.Entities;

namespace NextTurn.Infrastructure.Persistence.Configurations.Auth;

/// <summary>
/// EF Core Fluent API configuration for the User entity.
/// Maps the User domain object to the database schema.
/// Kept in Infrastructure — Domain never knows how it's persisted.
/// </summary>
public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");

        builder.HasKey(u => u.Id);

        builder.Property(u => u.Id)
            .ValueGeneratedNever(); // Guid is generated by User.Create(), not the database

        builder.Property(u => u.TenantId)
            .IsRequired();

        builder.Property(u => u.Name)
            .IsRequired()
            .HasMaxLength(100);

        // EmailAddress is a value object — EF Core maps it as an "owned entity"
        // Properties of the owned type become columns in the Users table.
        // Default column name: "Email_Value" (owned navigation "Email" + property "Value")
        builder.OwnsOne(u => u.Email, emailBuilder =>
        {
            emailBuilder.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(254);
        });

        builder.Property(u => u.Phone)
            .HasMaxLength(20);

        builder.Property(u => u.PasswordHash)
            .IsRequired()
            .HasMaxLength(255);

        builder.Property(u => u.CreatedAt)
            .IsRequired();

        builder.Property(u => u.IsActive)
            .IsRequired()
            .HasDefaultValue(true);

        // Unique index: one email address per tenant
        // Two different tenants CAN have a user with the same email (separate organisations)
        // "Email" refers to the column name defined in OwnsOne above (HasColumnName("Email"))
        builder.HasIndex("TenantId", "Email_Value")
            .IsUnique()
            .HasDatabaseName("IX_Users_TenantId_Email");
    }
}
