using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using NextTurn.Domain.Auth;
using NextTurn.Domain.Auth.Entities;

namespace NextTurn.Infrastructure.Persistence.Configurations.Auth;

/// <summary>
/// EF Core Fluent API configuration for the User entity.
/// Maps the User domain object to the database schema.
/// Kept in Infrastructure — Domain never knows how it's persisted.
/// </summary>
public class UserConfiguration : IEntityTypeConfiguration<User>
{
    public void Configure(EntityTypeBuilder<User> builder)
    {
        builder.ToTable("Users");

        builder.HasKey(u => u.Id);

        builder.Property(u => u.Id)
            .ValueGeneratedNever(); // Guid is generated by User.Create(), not the database

        builder.Property(u => u.TenantId)
            .IsRequired()
            .HasColumnName("TenantId"); // explicit: prevents renaming when OwnsOne mirrors this column

        builder.Property(u => u.Name)
            .IsRequired()
            .HasMaxLength(100);

        // EmailAddress is a value object — EF Core maps it as an "owned entity".
        // Properties of the owned type become columns in the Users table (table splitting).
        // We explicitly name the column "Email" (overriding the default "Email_Value").
        //
        // The composite unique index (TenantId, Email) is defined INSIDE the OwnsOne block
        // because HasIndex on the outer User builder cannot resolve owned-entity columns by
        // property name. We mirror TenantId as a shadow property on the owned type
        // (pointing at the same "TenantId" column) so the index builder can reference it.
        // This is an explicitly supported pattern in EF Core table-splitting.
        builder.OwnsOne(u => u.Email, emailBuilder =>
        {
            emailBuilder.Property(e => e.Value)
                .IsRequired()
                .HasMaxLength(254)
                .HasColumnName("Email");

            // Shadow property: mirrors User.TenantId into the owned-entity scope so we can
            // build a composite index that spans both the owner and owned columns.
            emailBuilder.Property<Guid>("TenantId")
                .HasColumnName("TenantId");

            // Unique index: one email address per tenant.
            // Two different tenants CAN share the same email (row-level isolation).
            // Property names ("Value", "TenantId") resolve to columns ("Email", "TenantId").
            emailBuilder.HasIndex("TenantId", "Value")
                .IsUnique()
                .HasDatabaseName("IX_Users_TenantId_Email");
        });

        builder.Property(u => u.Phone)
            .HasMaxLength(20);

        builder.Property(u => u.PasswordHash)
            .IsRequired()
            .HasMaxLength(255);

        builder.Property(u => u.CreatedAt)
            .IsRequired();

        builder.Property(u => u.IsActive)
            .IsRequired()
            .HasDefaultValue(true);

        // ── Role & security columns (added in NT-11) ──────────────────────────

        // Store role as a string (e.g. "User", "Staff") rather than an integer.
        // String storage is self-documenting in the database and survives enum reordering.
        builder.Property(u => u.Role)
            .IsRequired()
            .HasMaxLength(20)
            .HasDefaultValue(UserRole.User)
            .HasConversion<string>();

        builder.Property(u => u.FailedLoginAttempts)
            .IsRequired()
            .HasDefaultValue(0);

        // Nullable — null means the account is not locked.
        builder.Property(u => u.LockoutUntil);

        // Always false in Sprint 1. Column reserved for future MFA implementation.
        builder.Property(u => u.MfaEnabled)
            .IsRequired()
            .HasDefaultValue(false);
    }
}
